from typing import List, Optional

class UnigramTokenizer:
    def __init__(self, vocab_file: Optional[str] = None) -> None: ...
    
    @staticmethod
    def load(vocab_file: str) -> "UnigramTokenizer": ...
    
    def encode(self, data: bytes) -> List[int]: ...
    
    def decode(self, tokens: List[int]) -> bytes: ...
    
    def save(self, vocab_file: str) -> None: ...
    
    def train(self, file_path: str, vocab_size: int, min_freq: int) -> None: ...
    
    def vocab_size(self) -> int: ...
